# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: npm config set @bentley:registry pkgs.dev.azure.com/bentleycs/_packaging/Packages/npm/registry/
  displayName: 'NPM config set registry'

- script: npm config set //pkgs.dev.azure.com/bentleycs/_packaging/Packages/npm/registry/:username Default
  displayName: 'NPM config set username'

- script: npm config set //pkgs.dev.azure.com/bentleycs/_packaging/Packages/npm/registry/:_password $NPM_TOKEN
  displayName: 'NPM config set password'
  env: 
    NPM_TOKEN: $(NPM_PAT)
          
- script: npm config set //pkgs.dev.azure.com/bentleycs/_packaging/Packages/npm/registry/:email user@bentley.com
  displayName: 'NPM config set email'

- script: npm config set //pkgs.dev.azure.com/bentleycs/_packaging/Packages/npm/registry/:always-auth true
  displayName: 'NPM config set always auth'
          
- script: npm config set //pkgs.dev.azure.com/bentleycs/_packaging/Packages/npm/registry/:always-auth true
  displayName: 'NPM config set always auth'

- script: npm config set //pkgs.dev.azure.com/bentleycs/_packaging/Packages/npm/:username Default
  displayName: 'NPM config set username packages'

- script: npm config set //pkgs.dev.azure.com/bentleycs/_packaging/Packages/npm/:_password $NPM_TOKEN
  displayName: 'NPM config set password packages'
  env: 
    NPM_TOKEN: $(NPM_PAT)

- script: npm config set //pkgs.dev.azure.com/bentleycs/_packaging/Packages/npm/:email user@bentley.com
  displayName: 'NPM config set email packages'

- script: npm config set //pkgs.dev.azure.com/bentleycs/_packaging/Packages/npm/:always-auth true
  displayName: 'NPM config set always auth packages'

- script: node common/scripts/install-run-rush.js install
  displayName: 'rush install'

- script: node common/scripts/install-run-rush.js rebuild
  displayName: 'rush rebuild'

- script: git config --local user.name "iTwinViewerWorkflow"
  displayName: 'git config username'

- script: git config --local user.email "itwinviewer@users.noreply.github.com"
  displayName: 'git config email'

- script: node common/scripts/install-run-rush.js version --bump --target-branch main 
  displayName: 'rush version'

- script: node common/scripts/install-run-rush.js publish --include-all --set-access-level public --apply --publish --npm-auth-token $NPM_TOKEN --target-branch main --registry https://pkgs.dev.azure.com/bentleycs/_packaging/Packages/npm/registry/
  displayName: 'rush publish'
  env: 
    NPM_TOKEN: $(NPM_PAT)


